
export const ADD_INGREDIENT = "INGREDIENTS/ADD";
export const REMOVE_LAST_INGREDIENT = "INGREDIENTS/REMOVE_LAST";
export const REMOVE_INGREDIENT_BY_ID = "INGREDIENTS/REMOVE_BY_ID";

export const SET_MENU = "INGREDIENTS/SET_MENU";
export const MENU_FETCH_ERROR = "INGREDIENTS/MENU_FETCH_ERROR";
