
export const CREATE_ORDER_START = "ORDERS/CREATE_START";
export const CREATE_ORDER_SUCCESS = "ORDERS/CREATE_SUCCESS";
export const CREATE_ORDER_FAIL = "ORDERS/CREATE_FAIL";

export const READ_ORDERS_START = "ORDERS/READ_START";
export const READ_ORDERS_SUCCESS = "ORDERS/READ_SUCCESS";
export const READ_ORDERS_FAIL = "ORDERS/READ_FAIL";
